(define taxrate 1.0625)
(define (formatString number)
;;Its close :) 
(/ (round (* 100 (+ number .0001))) 100)
)
(define (checkout value subtotal)
   ( + (let loop ((i 0))
   (display "Please Enter an Item:")
   (let ((number (read)))
   (if (equal? number value)
      i
      (loop (+ i number)))))
  subtotal)
)
(define (StartPOS)
(display "*****   WELCOME TO SUPER AWESOME POS *******")(newline)
(display "********************************************")(newline)
(display "Gives a running total. Enter 0 to exit")(newline)
(define TotalBeforeTax (checkout 0 0))
(display "Your Total After tax:$")
(display (formatString (* TotalBeforeTax taxrate)))(newline)
"Finished Now System Exit"
)

